version: "3"
services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: docker-adonis
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    restart: always
  app:
    container_name: app
    image: app:v1.0.1
    ports:
      - "3333:3333"
    depends_on:
      - database
    links:
      - database
